// Runs after `expo export --platform web`. Expo SDK 57's static export only
// emits a browser <title> and favicon, so an iOS "Add to Home Screen" gets a
// gray auto-generated letter tile instead of the real app icon. This copies
// the app icon to the web root and injects the Apple/PWA head tags iOS and
// Android use for home-screen installs.
const fs = require('fs');
const path = require('path');

const dist = path.join(__dirname, '..', 'dist');
const htmlPath = path.join(dist, 'index.html');

// The stealth disguise name — this is what shows under the home-screen icon.
const APP_NAME = '가계부';
const THEME_COLOR = '#b2c7da';

// 1. Copy the budget-app home-screen icon (assets/webicon.png, generated by
//    scripts/gen-webicon.js) to the web root. iOS scales it down and, even
//    without a link tag, auto-detects /apple-touch-icon.png; we add the
//    explicit tag too for good measure.
fs.copyFileSync(
  path.join(__dirname, '..', 'assets', 'webicon.png'),
  path.join(dist, 'apple-touch-icon.png'),
);

// 2. A minimal PWA manifest so Android's "Add to Home Screen" also gets a
//    proper icon and name.
const manifest = {
  name: APP_NAME,
  short_name: APP_NAME,
  start_url: '/',
  display: 'standalone',
  background_color: THEME_COLOR,
  theme_color: THEME_COLOR,
  // Android install needs 192 and 512 icons; the file is larger and the
  // browser downscales it.
  icons: [
    { src: '/apple-touch-icon.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
    { src: '/apple-touch-icon.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
    { src: '/apple-touch-icon.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
  ],
};
fs.writeFileSync(path.join(dist, 'manifest.webmanifest'), JSON.stringify(manifest));

// 3. Inject the head tags right before </head>.
const tags = [
  '<link rel="apple-touch-icon" href="/apple-touch-icon.png"/>',
  '<meta name="apple-mobile-web-app-capable" content="yes"/>',
  '<meta name="mobile-web-app-capable" content="yes"/>',
  `<meta name="apple-mobile-web-app-title" content="${APP_NAME}"/>`,
  '<meta name="apple-mobile-web-app-status-bar-style" content="default"/>',
  `<meta name="theme-color" content="${THEME_COLOR}"/>`,
  '<link rel="manifest" href="/manifest.webmanifest"/>',
  // Fully lock the document so iOS Safari can't scroll the page itself when the
  // keyboard opens (that document-scroll was what made the chat jump up). The
  // app is a fixed shell; inner React Native ScrollViews still scroll normally.
  '<style>html,body{position:fixed;top:0;left:0;right:0;bottom:0;width:100%;height:100%;overflow:hidden;overscroll-behavior:none;}</style>',
].join('');

let html = fs.readFileSync(htmlPath, 'utf8');

// 4. Harden the viewport meta. Expo emits a plain viewport; on iOS Safari
//    focusing an input with font-size < 16px auto-zooms the whole page (which
//    then clips the UI), and env(safe-area-inset-*) only resolves when
//    viewport-fit=cover is set. maximum-scale=1 + user-scalable=no stops the
//    zoom; viewport-fit=cover lets the tab bar pad past the home indicator.
const VIEWPORT =
  '<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, viewport-fit=cover, interactive-widget=resizes-content"/>';
html = html.replace(/<meta name="viewport"[^>]*>/, VIEWPORT);

if (!html.includes('apple-touch-icon')) {
  html = html.replace('</head>', tags + '</head>');
}
fs.writeFileSync(htmlPath, html);
console.log('postexport-web: injected home-screen icon + PWA head tags + hardened viewport');
